FROM debian:bookworm-slim

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
    apache2 \
    python3 \
    python3-pip \
    python3-dev \
    python3-venv \
    libmariadb-dev \
    libapache2-mod-wsgi-py3 \
    pkg-config \
    gcc

ENV TZ=America/Mexico_City
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./requirements-dev.txt /app/requirements-dev.txt

WORKDIR /app

RUN python3 -m venv /env
ENV PATH="/env/bin:$PATH"

RUN /env/bin/pip install --upgrade pip
RUN /env/bin/pip install -r /app/requirements-dev.txt

# El código llega por volumen en docker-compose, no se copia aquí
CMD ["apachectl", "-D", "FOREGROUND"]