# Generated by Django 5.2.14 on 2026-06-03 22:31

import django.db.models.deletion
import lumat_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicial')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Final')),
                ('archivo_pdf', models.FileField(upload_to='calendarios_guardados/', verbose_name='Archivo PDF')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
            ],
            options={
                'verbose_name': 'Calendario Guardado',
                'verbose_name_plural': 'Calendarios Guardados',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('semestre', models.CharField(default=1, max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('firma', models.ImageField(upload_to='firmas/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembro1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembro1', to='lumat_app.docente', verbose_name='Primer miembro')),
                ('miembro2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembro2', to='lumat_app.docente', verbose_name='Segundo miembro')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumat_app.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Seminario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('actaComite', models.FileField(blank=True, null=True, upload_to='actas/')),
                ('actaAlumno', models.FileField(blank=True, null=True, upload_to='actas_alumno/')),
                ('numero', models.PositiveSmallIntegerField()),
                ('periodo', models.PositiveSmallIntegerField(default=1)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumat_app.alumno')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumat_app.comite')),
            ],
            options={
                'ordering': ['numero', 'periodo'],
            },
        ),
        migrations.CreateModel(
            name='FormularioComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_comite_encuentra', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('dictamen', models.TextField(blank=True)),
                ('propuestas', models.TextField(blank=True)),
                ('calificacion_tutor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calificacion_miembro1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calificacion_miembro2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('firma_tutor', models.BooleanField(default=False)),
                ('firma_miembro1', models.BooleanField(default=False)),
                ('firma_miembro2', models.BooleanField(default=False)),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado_general', models.CharField(choices=[('rechazado', 'Rechazado'), ('pendiente', 'Pendiente'), ('completo', 'Completo')], default='pendiente', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('seminario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_comite', to='lumat_app.seminario')),
            ],
            options={
                'verbose_name': 'Formulario de Comité',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=lumat_app.models.evidencia_upload_path)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('pdf', 'PDF'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('seminario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='lumat_app.seminario')),
            ],
            options={
                'ordering': ['subido_en'],
            },
        ),
        migrations.CreateModel(
            name='CalifSeminario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumat_app.docente')),
                ('seminario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumat_app.seminario')),
            ],
        ),
        migrations.CreateModel(
            name='ActaAlumnoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_principal', models.CharField(max_length=200)),
                ('reuniones_tutor', models.PositiveSmallIntegerField(default=0)),
                ('reuniones_comite', models.PositiveSmallIntegerField(default=0)),
                ('coloquios', models.PositiveSmallIntegerField(default=0)),
                ('cursos', models.TextField(blank=True)),
                ('articulos', models.TextField(blank=True)),
                ('eventos', models.TextField(blank=True)),
                ('plan_siguiente', models.TextField()),
                ('comentarios', models.TextField(blank=True)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('seminario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta_data', to='lumat_app.seminario')),
            ],
            options={
                'verbose_name': 'Datos de acta del alumno',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCambioTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_tutor', to='lumat_app.alumno')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='seminario',
            constraint=models.UniqueConstraint(fields=('alumno', 'numero', 'periodo'), name='unique_seminario_periodo'),
        ),
    ]
