# Generated by Django 5.2.15 on 2026-06-27 00:14

import django.core.validators
import django.db.models.deletion
import lumat_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicial')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Final')),
                ('archivo_pdf', models.FileField(upload_to='calendarios_guardados/', verbose_name='Archivo PDF')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
            ],
            options={
                'verbose_name': 'Calendario Guardado',
                'verbose_name_plural': 'Calendarios Guardados',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('semestre', models.CharField(default=1, max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('posgrado', models.CharField(choices=[('maestria', 'Maestría'), ('doctorado', 'Doctorado')], max_length=50)),
                ('periodo_inicio_estudios', models.CharField(max_length=50)),
                ('periodo_fin_estudios', models.CharField(max_length=50)),
                ('acta_examen_titulacion', models.FileField(blank=True, null=True, upload_to='actas_examen_titulacion/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Acta de Examen de Titulación')),
                ('linea_investigacion', models.CharField(choices=[('Materia condensada y energía', 'Materia condensada y energía'), ('Óptica y fotónica', 'Óptica y fotónica'), ('Agua y su manejo sostenible', 'Agua y su manejo sostenible')], max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('posgrado_o_universidad_anterior', models.CharField(max_length=100)),
                ('proyecto_investigacion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('egresado', 'Egresado'), ('dado de baja', 'Dado de baja'), ('baja temporal', 'Baja Temporal')], default='activo', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('firma', models.ImageField(upload_to='firmas/')),
                ('telefono', models.CharField(max_length=20)),
                ('red_social_investigacion', models.URLField()),
                ('ultimo_grado_estudio', models.CharField(max_length=100)),
                ('universidad_o_centro', models.CharField(max_length=100)),
                ('facultad_o_instituto', models.CharField(max_length=100)),
                ('nombramiento_sni', models.FileField(blank=True, null=True, upload_to='nombramientos_sni/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Nombramiento SNI')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesor', to='lumat_app.docente', verbose_name='asesor de tesis')),
                ('coodirector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coodirector', to='lumat_app.docente', verbose_name='coodirector de tesis')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='lumat_app.docente', verbose_name='director de tesis')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumat_app.docente')),
            ],
        ),
        migrations.CreateModel(
            name='RetribucionSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='retribucion_social/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Archivo PDF')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción del documento')),
                ('subido_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retribuciones_sociales', to='lumat_app.alumno', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Retribución Social',
                'verbose_name_plural': 'Retribuciones Sociales',
                'ordering': ['-subido_en'],
            },
        ),
        migrations.CreateModel(
            name='Seminario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('actaComite', models.FileField(blank=True, null=True, upload_to='actas/')),
                ('actaAlumno', models.FileField(blank=True, null=True, upload_to='actas_alumno/')),
                ('numero', models.PositiveSmallIntegerField()),
                ('periodo', models.PositiveSmallIntegerField(default=1)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumat_app.alumno')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumat_app.comite')),
            ],
            options={
                'ordering': ['numero', 'periodo'],
            },
        ),
        migrations.CreateModel(
            name='FormularioComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_comite_encuentra', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('dictamen', models.TextField(blank=True)),
                ('propuestas', models.TextField(blank=True)),
                ('calificacion_tutor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calificacion_miembro1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calificacion_miembro2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('firma_tutor', models.BooleanField(default=False)),
                ('firma_miembro1', models.BooleanField(default=False)),
                ('firma_miembro2', models.BooleanField(default=False)),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado_general', models.CharField(choices=[('rechazado', 'Rechazado'), ('pendiente', 'Pendiente'), ('completo', 'Completo')], default='pendiente', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('seminario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_comite', to='lumat_app.seminario')),
            ],
            options={
                'verbose_name': 'Formulario de Comité',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=lumat_app.models.evidencia_upload_path)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('pdf', 'PDF'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('seminario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='lumat_app.seminario')),
            ],
            options={
                'ordering': ['subido_en'],
            },
        ),
        migrations.CreateModel(
            name='ActaAlumnoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_principal', models.CharField(max_length=200)),
                ('reuniones_tutor', models.PositiveSmallIntegerField(default=0)),
                ('reuniones_comite', models.PositiveSmallIntegerField(default=0)),
                ('coloquios', models.PositiveSmallIntegerField(default=0)),
                ('cursos', models.TextField(blank=True)),
                ('articulos', models.TextField(blank=True)),
                ('eventos', models.TextField(blank=True)),
                ('plan_siguiente', models.TextField()),
                ('comentarios', models.TextField(blank=True)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('seminario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta_data', to='lumat_app.seminario')),
            ],
            options={
                'verbose_name': 'Datos de acta del alumno',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCambioTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_tutor', to='lumat_app.alumno')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='seminario',
            constraint=models.UniqueConstraint(fields=('alumno', 'numero', 'periodo'), name='unique_seminario_periodo'),
        ),
    ]
