# Generated by Django 5.2.13 on 2026-04-17 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('semestre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('firma', models.ImageField(upload_to='firmas/')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('miembro1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='miembro1', to='lumat_app.docente')),
                ('miembro2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='miembro2', to='lumat_app.docente')),
                ('tutor', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='lumat_app.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Seminario',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('calificacion', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=4, null=True)),
                ('actaComite', models.FileField(
                    blank=True, null=True, upload_to='actas/')),
                ('actaAlumno', models.FileField(
                    blank=True, null=True, upload_to='actas_alumno/')),
                ('alumno', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='lumat_app.alumno')),
                ('comite', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='lumat_app.comite')),
            ],
        ),
        migrations.CreateModel(
            name='CalifSeminario',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(
                    decimal_places=2, max_digits=4)),
                ('docente', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='lumat_app.docente')),
                ('seminario', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='lumat_app.seminario')),
            ],
        ),
    ]
