# Generated by Django 5.2.13 on 2026-04-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(
                blank=True, max_length=8, null=True, unique=True),
        ),
    ]
