# Generated by Django 5.2.14 on 2026-05-28 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumat_app', '0002_alter_alumno_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150,
                 verbose_name='Nombre del Periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicial')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Final')),
                ('archivo_pdf', models.FileField(
                    upload_to='calendarios_guardados/', verbose_name='Archivo PDF')),
                ('fecha_creacion', models.DateTimeField(
                    auto_now_add=True, verbose_name='Fecha de Generación')),
            ],
            options={
                'verbose_name': 'Calendario Guardado',
                'verbose_name_plural': 'Calendarios Guardados',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='comite',
            name='miembro1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='miembro1', to='lumat_app.docente', verbose_name='Primer miembro'),
        ),
        migrations.AlterField(
            model_name='comite',
            name='miembro2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='miembro2', to='lumat_app.docente', verbose_name='Segundo miembro'),
        ),
    ]
