# Generated by Django 5.2.14 on 2026-05-28 07:48

import django.db.models.deletion
import lumat_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumat_app', '0002_alter_alumno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comite',
            name='miembro1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='miembro1', to='lumat_app.docente', verbose_name='Primer miembro'),
        ),
        migrations.AlterField(
            model_name='comite',
            name='miembro2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='miembro2', to='lumat_app.docente', verbose_name='Segundo miembro'),
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(
                    upload_to=lumat_app.models.evidencia_upload_path)),
                ('tipo', models.CharField(choices=[
                 ('imagen', 'Imagen'), ('pdf', 'PDF'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('seminario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='evidencias', to='lumat_app.seminario')),
            ],
            options={
                'ordering': ['subido_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCambioTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), (
                    'rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='solicitudes_tutor', to='lumat_app.alumno')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='SeminarioNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='seminarios_numerados', to='lumat_app.alumno')),
                ('seminario', models.OneToOneField(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, related_name='numero_obj', to='lumat_app.seminario')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('alumno', 'numero')},
            },
        ),
    ]
