# Generated by Django 5.2.14 on 2026-05-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumat_app', '0003_alter_comite_miembro1_alter_comite_miembro2_and_more'),
        ('lumat_app', '0003_calendariogenerado_alter_comite_miembro1_and_more'),
    ]

    operations = [
    ]
