# Generated by Django 5.2.14 on 2026-05-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumat_app', '0004_merge_20260528_0230'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seminarionumero',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seminarionumero',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='seminarionumero',
            name='seminario',
        ),
        migrations.AlterModelOptions(
            name='seminario',
            options={'ordering': ['numero', 'periodo']},
        ),
        migrations.AddField(
            model_name='seminario',
            name='numero',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminario',
            name='periodo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='seminario',
            constraint=models.UniqueConstraint(
                fields=('alumno', 'numero', 'periodo'), name='unique_seminario_periodo'),
        ),
        migrations.DeleteModel(
            name='SeminarioNumero',
        ),
    ]
