# Generated by Django 5.2.14 on 2026-06-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumat_app', '0005_alter_seminarionumero_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminario',
            name='calificacionMiembro1',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='seminario',
            name='calificacionMiembro2',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='seminario',
            name='calificacionTutor',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='FormularioComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('el_comite_encuentra', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('dictamen', models.TextField(blank=True)),
                ('propuestas', models.TextField(blank=True)),
                ('calificacion_tutor', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calificacion_miembro1', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calificacion_miembro2', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=4, null=True)),
                ('firma_tutor', models.BooleanField(default=False)),
                ('firma_miembro1', models.BooleanField(default=False)),
                ('firma_miembro2', models.BooleanField(default=False)),
                ('calificacion_final', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado_general', models.CharField(choices=[('rechazado', 'Rechazado'), (
                    'pendiente', 'Pendiente'), ('completo', 'Completo')], default='pendiente', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('seminario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='formulario_comite', to='lumat_app.seminario')),
            ],
            options={
                'verbose_name': 'Formulario de Comité',
            },
        ),
    ]
