# Generated by Django 5.2.14 on 2026-06-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumat_app', '0006_seminario_calificacionmiembro1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminario',
            name='calificacionMiembro1',
        ),
        migrations.RemoveField(
            model_name='seminario',
            name='calificacionMiembro2',
        ),
        migrations.RemoveField(
            model_name='seminario',
            name='calificacionTutor',
        ),
        migrations.AddField(
            model_name='formulariocomite',
            name='pdf_generado',
            field=models.FileField(blank=True, null=True, upload_to='pdfs_comite/', verbose_name='PDF del informe del comité'),
        ),
        migrations.AddField(
            model_name='formulariocomite',
            name='pdf_generado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
