# Generated by Django 5.2.14 on 2026-06-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumat_app', '0006_seminario_calificacionmiembro1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminario',
            name='calificacionMiembro1',
        ),
        migrations.RemoveField(
            model_name='seminario',
            name='calificacionMiembro2',
        ),
        migrations.RemoveField(
            model_name='seminario',
            name='calificacionTutor',
        ),
        migrations.AlterField(
            model_name='seminario',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seminario',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
