# Generated by Django 5.2.14 on 2026-06-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumat_app', '0007_remove_seminario_calificacionmiembro1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariocomite',
            name='pdf_generado',
        ),
        migrations.RemoveField(
            model_name='formulariocomite',
            name='pdf_generado_en',
        ),
    ]
