# Generated by Django 5.2.14 on 2026-06-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumat_app', '0009_actaalumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actaalumno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='no_cuenta',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='nombre_completo',
        ),
        migrations.AlterField(
            model_name='actaalumno',
            name='actividad_principal',
            field=models.CharField(choices=[('investigacion', 'Investigación'), ('docencia', 'Docencia'), ('ambos', 'Ambos'), ('otro', 'Otro')], default='investigacion', max_length=50),
        ),
        migrations.AlterField(
            model_name='actaalumno',
            name='articulos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='actaalumno',
            name='cursos_descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='actaalumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actaalumno',
            name='plan_estudios',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='actaalumno',
            name='semestre_ingreso',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
