# Generated by Django 5.2.14 on 2026-06-03 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumat_app', '0010_remove_actaalumno_email_remove_actaalumno_no_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actaalumno',
            options={'verbose_name': 'Datos de acta del alumno'},
        ),
        migrations.RenameField(
            model_name='actaalumno',
            old_name='comentarios_adicionales',
            new_name='comentarios',
        ),
        migrations.RenameField(
            model_name='actaalumno',
            old_name='cursos_descripcion',
            new_name='cursos',
        ),
        migrations.RenameField(
            model_name='actaalumno',
            old_name='eventos_descripcion',
            new_name='eventos',
        ),
        migrations.RenameField(
            model_name='actaalumno',
            old_name='fecha_creacion',
            new_name='generado_en',
        ),
        migrations.RenameField(
            model_name='actaalumno',
            old_name='plan_actividades',
            new_name='plan_siguiente',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='actividad_principal_otro',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='asistencia_coloquio',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='cursos_pcf',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='cvU',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='eventos_asistio',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='examen_candidatura',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='examen_candidatura_fecha',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='examenes_descripcion',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='examenes_predoctorales',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='no_becario_conacyt',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='otras_actividades',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='pais_origen',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='plan_estudios',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='reuniones_comite_tutor',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='reuniones_tutor_principal',
        ),
        migrations.RemoveField(
            model_name='actaalumno',
            name='semestre_ingreso',
        ),
        migrations.AddField(
            model_name='actaalumno',
            name='coloquios',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actaalumno',
            name='reuniones_comite',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actaalumno',
            name='reuniones_tutor',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actaalumno',
            name='actividad_principal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='actaalumno',
            name='seminario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta_data', to='lumat_app.seminario'),
        ),
    ]
