# Generated by Django 5.2.14 on 2026-06-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumat_app', '0011_alter_actaalumno_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActaAlumno',
            new_name='ActaAlumnoData',
        ),
    ]
