# Generated by Django 5.2.14 on 2026-06-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumat_app', '0012_rename_actaalumno_actaalumnodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='semestre',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
